metadata:
    labels:
        org.apache.camel.karavan/type: project
spec:
  replicas: 1
  template:
    metadata:
      labels:
        org.apache.camel.karavan/type: project
    spec:
      serviceAccount: karavan-integration
      containers:
        - name: exemplo-camel
          env:
            - name: JAVA_TOOL_OPTIONS
              value: >
                -Dotel.java.global-autoconfigure.enabled=true
                -Dotel.metrics.exporter=otlp
                -Dotel.traces.exporter=otlp
                -Dotel.logs.exporter=otlp
                -Dotel.exporter.otlp.endpoint=http://otel-collector.monitoring:4317
                -Dotel.service.name=exemplo-camel
                -Dotel.instrumentation.runtime-metrics.enabled=true
                -Dotel.instrumentation.jvm-metrics.enabled=true
            - name: URL_NINTEGRATOR     
              valueFrom:
                configMapKeyRef:
                  name: exemplo-camel
                  key: URL_NINTEGRATOR
            - name: AMBIENTE     
              valueFrom:
                configMapKeyRef:
                  name: exemplo-camel
                  key: AMBIENTE