metadata:
    labels:
        org.apache.camel.karavan/type: project
spec:
  replicas: 1
  template:
    metadata:
      labels:
        org.apache.camel.karavan/type: project
    spec:
      serviceAccount: karavan-integration
      containers:
        - name: exemplo-camel
          image: registry.services-dev.nexdom.tec.br/karavan/${PROJECT_ID}:latest
          envFrom:
            - configMapRef:
                name: ${PROJECT_ID}
          env:
            - name: JAVA_TOOL_OPTIONS
              value: >
                -Dotel.java.global-autoconfigure.enabled=true
                -Dotel.metrics.exporter=otlp
                -Dotel.traces.exporter=otlp
                -Dotel.logs.exporter=otlp
                -Dotel.exporter.otlp.endpoint=http://otel-collector.monitoring:4317
                -Dotel.service.name=exemplo-camel
                -Dotel.instrumentation.runtime-metrics.enabled=true
                -Dotel.instrumentation.jvm-metrics.enabled=true
