metadata:
    labels:
        org.apache.camel.karavan/type: project
spec:
  replicas: 1
  template:
    metadata:
      labels:
        org.apache.camel.karavan/type: project
    spec:
      serviceAccount: karavan-integration
      containers:
        - name: integracao-prime
          env:
            - name: JAVA_TOOL_OPTIONS
              value: >
                -Dotel.java.global-autoconfigure.enabled=true
                -Dotel.metrics.exporter=otlp
                -Dotel.traces.exporter=otlp
                -Dotel.logs.exporter=otlp
                -Dotel.exporter.otlp.endpoint=http://otel-collector.monitoring:4317
                -Dotel.service.name=integracao-prime
                -Dotel.instrumentation.runtime-metrics.enabled=true
                -Dotel.instrumentation.jvm-metrics.enabled=true
          resources:
            limits:
              cpu: 100m
              memory: 500Mi
            requests:
              cpu: 50m
              memory: 350Mi
              