spec:
  replicas: 1
  template:
    spec:
      serviceAccount: karavan
      containers:
        - name: integracao-prime
          image: integracao-prime
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_TOOL_OPTIONS
              value: >
                -Dotel.java.global-autoconfigure.enabled=true
                -Dotel.metrics.exporter=otlp
                -Dotel.traces.exporter=otlp
                -Dotel.logs.exporter=otlp
                -Dotel.exporter.otlp.endpoint=http://otel-collector.monitoring:4317
                -Dotel.service.name=integracao-prime
                -Dotel.instrumentation.runtime-metrics.enabled=true
                -Dotel.instrumentation.jvm-metrics.enabled=true