services:
  consultas:
    container_name: consultas
    environment:
      JAVA_TOOL_OPTIONS: -Dotel.java.global-autoconfigure.enabled=true -Dotel.metrics.exporter=none
        -Dotel.traces.exporter=otlp -Dotel.logs.exporter=otlp -Dotel.exporter.otlp.endpoint=http://otel-collector:4317
        -Dotel.service.name=consultas
    image: localhost:5555/karavan/consultas:latest
    networks:
    - karavan
    ports:
    - 8083:8080
    restart: always
