services:
  consultas:
    container_name: consultas
    image: localhost:5555/karavan/consultas:latest
    networks:
        - karavan
    environment:
        JAVA_TOOL_OPTIONS: "-Dotel.java.global-autoconfigure.enabled=true -Dotel.metrics.exporter=otlp -Dotel.traces.exporter=otlp -Dotel.logs.exporter=otlp"
    ports:
     - 8083:8080
    restart: always
