services:
  consultas:
    container_name: consultas
    image: localhost:5555/karavan/consultas:latest
    networks:
        - karavan
    environment:
        JAVA_TOOL_OPTIONS: "-Dotel.java.global-autoconfigure.enabled=true -Dotel.metrics.exporter=none -Dotel.traces.exporter=otlp -Dotel.logs.exporter=otlp -Dotel.exporter.otlp.endpoint=http://otel-collector:4317 -Dotel.service.name=consultas"
    ports:
     - 8083:8080
    restart: always
  promtail:
    container_name: promtail
    image: grafana/promtail:2.9.3
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
      - /etc/machine-id:/etc/machine-id:ro
      - ./promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - karavan
      