services:
  consultas:
    container_name: consultas
    image: localhost:5555/karavan/consultas:latest
    networks:
    - karavan
    environment:
    - JAVA_TOOL_OPTIONS=-Dotel.java.global-autoconfigure.enabled=true -Dotel.metrics.exporter=none -Dotel.traces.exporter=none -Dotel.logs.exporter=none
    - OTEL_SERVICE_NAME="camel"
    ports:
    - 8083:8080
    - 8084:8080
    restart: always
