<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="http://Benner.Corporativo.WebServices.DataContracts/2010/10" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" targetNamespace="http://Benner.Corporativo.WebServices.DataContracts/2010/10" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:documentation xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">Integração do módulo financeiro do sistema Corporativo</wsdl:documentation>
  <wsdl:types>
    <s:schema elementFormDefault="qualified" targetNamespace="http://Benner.Corporativo.WebServices.DataContracts/2010/10">
      <s:element name="Integrar">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="request" type="tns:IntegrarDocumentosRequest" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:complexType name="IntegrarDocumentosRequest">
        <s:complexContent mixed="false">
          <s:extension base="tns:FinanceiroRequest">
            <s:sequence>
              <s:element minOccurs="0" maxOccurs="1" name="Documentos" type="tns:ArrayOfDocumentoLayout" />
              <s:element minOccurs="1" maxOccurs="1" name="PodeExecutarParcial" type="s:boolean" />
            </s:sequence>
          </s:extension>
        </s:complexContent>
      </s:complexType>
      <s:complexType name="FinanceiroRequest">
        <s:complexContent mixed="false">
          <s:extension base="tns:Request" />
        </s:complexContent>
      </s:complexType>
      <s:complexType name="Request">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="1" name="Identificador" type="s:string" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="ArrayOfDocumentoLayout">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="unbounded" name="DocumentoLayout" nillable="true" type="tns:DocumentoLayout" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="DocumentoLayout">
        <s:complexContent mixed="false">
          <s:extension base="tns:LayoutBase">
            <s:sequence>
              <s:element minOccurs="0" maxOccurs="1" name="Identificador" type="s:string" />
              <s:element minOccurs="1" maxOccurs="1" name="DeveDesbloquearAposInclusao" type="s:boolean" />
              <s:element minOccurs="0" maxOccurs="1" name="Parcelas" type="tns:ArrayOfParcelaLayout" />
              <s:element minOccurs="0" maxOccurs="1" name="Lancamentos" type="tns:ArrayOfLancamentoLayout" />
              <s:element minOccurs="0" maxOccurs="1" name="Impostos" type="tns:ArrayOfDocumentoImpostoLayout" />
              <s:element minOccurs="0" maxOccurs="1" name="Tributos" type="tns:ArrayOfDocumentoTributoLayout" />
              <s:element minOccurs="0" maxOccurs="1" name="Apropriacoes" type="tns:ArrayOfDocumentoApropriacaoLayout" />
              <s:element minOccurs="0" maxOccurs="1" name="Retencoes" type="tns:ArrayOfRetencaoLayout" />
              <s:element minOccurs="0" maxOccurs="1" name="ExtratoUtilizacao" type="tns:ArrayOfDocumentoExtratoUtilizacaoLayout" />
              <s:element minOccurs="0" maxOccurs="1" name="UsuariosPlano" type="tns:ArrayOfDocumentoUsuariosPlanoLayout" />
            </s:sequence>
          </s:extension>
        </s:complexContent>
      </s:complexType>
      <s:complexType name="LayoutBase">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="1" name="Campos" type="tns:ArrayOfCampoLayout" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="ArrayOfCampoLayout">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="unbounded" name="CampoLayout" nillable="true" type="tns:CampoLayout" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="CampoLayout">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="1" name="Nome" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="Valor" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="DocumentoUsuariosPlanoLayout">
        <s:complexContent mixed="false">
          <s:extension base="tns:LayoutBase" />
        </s:complexContent>
      </s:complexType>
      <s:complexType name="DocumentoExtratoUtilizacaoLayout">
        <s:complexContent mixed="false">
          <s:extension base="tns:LayoutBase" />
        </s:complexContent>
      </s:complexType>
      <s:complexType name="RetencaoLayout">
        <s:complexContent mixed="false">
          <s:extension base="tns:LayoutBase" />
        </s:complexContent>
      </s:complexType>
      <s:complexType name="DocumentoApropriacaoLayout">
        <s:complexContent mixed="false">
          <s:extension base="tns:LayoutBase" />
        </s:complexContent>
      </s:complexType>
      <s:complexType name="DocumentoTributoLayout">
        <s:complexContent mixed="false">
          <s:extension base="tns:LayoutBase" />
        </s:complexContent>
      </s:complexType>
      <s:complexType name="DocumentoImpostoLayout">
        <s:complexContent mixed="false">
          <s:extension base="tns:LayoutBase" />
        </s:complexContent>
      </s:complexType>
      <s:complexType name="LancamentoCentroCustoLayout">
        <s:complexContent mixed="false">
          <s:extension base="tns:LayoutBase" />
        </s:complexContent>
      </s:complexType>
      <s:complexType name="LancamentoLayout">
        <s:complexContent mixed="false">
          <s:extension base="tns:LayoutBase">
            <s:sequence>
              <s:element minOccurs="0" maxOccurs="1" name="LancamentosCentroCusto" type="tns:ArrayOfLancamentoCentroCustoLayout" />
            </s:sequence>
          </s:extension>
        </s:complexContent>
      </s:complexType>
      <s:complexType name="ArrayOfLancamentoCentroCustoLayout">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="unbounded" name="LancamentoCentroCustoLayout" nillable="true" type="tns:LancamentoCentroCustoLayout" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="ParcelaLayout">
        <s:complexContent mixed="false">
          <s:extension base="tns:LayoutBase" />
        </s:complexContent>
      </s:complexType>
      <s:complexType name="ArrayOfParcelaLayout">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="unbounded" name="ParcelaLayout" nillable="true" type="tns:ParcelaLayout" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="ArrayOfLancamentoLayout">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="unbounded" name="LancamentoLayout" nillable="true" type="tns:LancamentoLayout" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="ArrayOfDocumentoImpostoLayout">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="unbounded" name="DocumentoImpostoLayout" nillable="true" type="tns:DocumentoImpostoLayout" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="ArrayOfDocumentoTributoLayout">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="unbounded" name="DocumentoTributoLayout" nillable="true" type="tns:DocumentoTributoLayout" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="ArrayOfDocumentoApropriacaoLayout">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="unbounded" name="DocumentoApropriacaoLayout" nillable="true" type="tns:DocumentoApropriacaoLayout" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="ArrayOfRetencaoLayout">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="unbounded" name="RetencaoLayout" nillable="true" type="tns:RetencaoLayout" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="ArrayOfDocumentoExtratoUtilizacaoLayout">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="unbounded" name="DocumentoExtratoUtilizacaoLayout" nillable="true" type="tns:DocumentoExtratoUtilizacaoLayout" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="ArrayOfDocumentoUsuariosPlanoLayout">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="unbounded" name="DocumentoUsuariosPlanoLayout" nillable="true" type="tns:DocumentoUsuariosPlanoLayout" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="DocumentoIntegradoLayout">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="1" name="Identificador" type="s:string" />
          <s:element minOccurs="1" maxOccurs="1" name="CodigoRetorno" type="s:int" />
          <s:element minOccurs="0" maxOccurs="1" name="Mensagem" type="s:string" />
          <s:element minOccurs="1" maxOccurs="1" name="Handle" type="s:long" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="Response">
        <s:sequence>
          <s:element minOccurs="1" maxOccurs="1" name="CodigoRetorno" type="s:int" />
          <s:element minOccurs="0" maxOccurs="1" name="Mensagem" type="s:string" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="FinanceiroResponse">
        <s:complexContent mixed="false">
          <s:extension base="tns:Response" />
        </s:complexContent>
      </s:complexType>
      <s:complexType name="IntegrarDocumentosResponse">
        <s:complexContent mixed="false">
          <s:extension base="tns:FinanceiroResponse">
            <s:sequence>
              <s:element minOccurs="0" maxOccurs="1" name="Documentos" type="tns:ArrayOfDocumentoIntegradoLayout" />
            </s:sequence>
          </s:extension>
        </s:complexContent>
      </s:complexType>
      <s:complexType name="ArrayOfDocumentoIntegradoLayout">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="unbounded" name="DocumentoIntegradoLayout" nillable="true" type="tns:DocumentoIntegradoLayout" />
        </s:sequence>
      </s:complexType>
      <s:element name="IntegrarResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="IntegrarResult" type="tns:IntegrarDocumentosResponse" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="IntegrarAgendado">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="request" type="tns:IntegrarDocumentosRequest" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="IntegrarAgendadoResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="IntegrarAgendadoResult" type="tns:AgendamentoResponse" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:complexType name="AgendamentoResponse">
        <s:complexContent mixed="false">
          <s:extension base="tns:FinanceiroResponse" />
        </s:complexContent>
      </s:complexType>
      <s:element name="Excluir">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="request" type="tns:FuncaoRequest" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:complexType name="FuncaoRequest">
        <s:complexContent mixed="false">
          <s:extension base="tns:FinanceiroRequest">
            <s:sequence>
              <s:element minOccurs="0" maxOccurs="1" name="Documentos" type="tns:ArrayOfIdentificadorLayout" />
              <s:element minOccurs="1" maxOccurs="1" name="PodeExecutarParcial" type="s:boolean" />
            </s:sequence>
          </s:extension>
        </s:complexContent>
      </s:complexType>
      <s:complexType name="ArrayOfIdentificadorLayout">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="unbounded" name="IdentificadorLayout" nillable="true" type="tns:IdentificadorLayout" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="IdentificadorLayout">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="1" name="Identificador" type="s:string" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="ResultadoFuncaoLayout">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="1" name="Identificador" type="s:string" />
          <s:element minOccurs="1" maxOccurs="1" name="CodigoRetorno" type="s:int" />
          <s:element minOccurs="0" maxOccurs="1" name="Mensagem" type="s:string" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="ArrayOfResultadoFuncaoLayout">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="unbounded" name="ResultadoFuncaoLayout" nillable="true" type="tns:ResultadoFuncaoLayout" />
        </s:sequence>
      </s:complexType>
      <s:element name="ExcluirResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="ExcluirResult" type="tns:FuncaoResponse" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:complexType name="FuncaoResponse">
        <s:complexContent mixed="false">
          <s:extension base="tns:FinanceiroResponse">
            <s:sequence>
              <s:element minOccurs="0" maxOccurs="1" name="Resultados" type="tns:ArrayOfResultadoFuncaoLayout" />
            </s:sequence>
          </s:extension>
        </s:complexContent>
      </s:complexType>
      <s:element name="ExcluirAgendado">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="request" type="tns:FuncaoRequest" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="ExcluirAgendadoResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="ExcluirAgendadoResult" type="tns:AgendamentoResponse" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="Bloquear">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="request" type="tns:FuncaoRequest" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="BloquearResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="BloquearResult" type="tns:FuncaoResponse" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="BloquearAgendado">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="request" type="tns:FuncaoRequest" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="BloquearAgendadoResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="BloquearAgendadoResult" type="tns:AgendamentoResponse" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="Desbloquear">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="request" type="tns:FuncaoRequest" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="DesbloquearResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="DesbloquearResult" type="tns:FuncaoResponse" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="DesbloquearAgendado">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="request" type="tns:FuncaoRequest" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="DesbloquearAgendadoResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="DesbloquearAgendadoResult" type="tns:AgendamentoResponse" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="Cancelar">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="request" type="tns:CancelamentoRequest" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:complexType name="CancelamentoRequest">
        <s:complexContent mixed="false">
          <s:extension base="tns:Request">
            <s:sequence>
              <s:element minOccurs="0" maxOccurs="1" name="Documentos" type="tns:ArrayOfCancelamentoLayout" />
              <s:element minOccurs="1" maxOccurs="1" name="PodeExecutarParcial" type="s:boolean" />
            </s:sequence>
          </s:extension>
        </s:complexContent>
      </s:complexType>
      <s:complexType name="ArrayOfCancelamentoLayout">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="unbounded" name="CancelamentoLayout" nillable="true" type="tns:CancelamentoLayout" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="CancelamentoLayout">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="1" name="Identificador" type="s:string" />
          <s:element minOccurs="1" maxOccurs="1" name="Operacao" type="s:int" />
          <s:element minOccurs="1" maxOccurs="1" name="Data" type="s:dateTime" />
          <s:element minOccurs="0" maxOccurs="1" name="Historico" type="s:string" />
        </s:sequence>
      </s:complexType>
      <s:element name="CancelarResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="CancelarResult" type="tns:FuncaoResponse" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="CancelarAgendado">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="request" type="tns:CancelamentoRequest" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="CancelarAgendadoResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="CancelarAgendadoResult" type="tns:AgendamentoResponse" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="ConsultarIntegracao">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="request" type="tns:ConsultarRequest" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:complexType name="ConsultarRequest">
        <s:complexContent mixed="false">
          <s:extension base="tns:FinanceiroRequest" />
        </s:complexContent>
      </s:complexType>
      <s:element name="ConsultarIntegracaoResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="ConsultarIntegracaoResult" type="tns:ConsultaIntegracaoResponse" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:complexType name="ConsultaIntegracaoResponse">
        <s:complexContent mixed="false">
          <s:extension base="tns:IntegrarDocumentosResponse">
            <s:sequence>
              <s:element minOccurs="1" maxOccurs="1" name="StatusExecucao" type="s:int" />
            </s:sequence>
          </s:extension>
        </s:complexContent>
      </s:complexType>
      <s:element name="ConsultarFuncao">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="request" type="tns:ConsultarRequest" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="ConsultarFuncaoResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="ConsultarFuncaoResult" type="tns:ConsultaFuncaoResponse" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:complexType name="ConsultaFuncaoResponse">
        <s:complexContent mixed="false">
          <s:extension base="tns:FuncaoResponse">
            <s:sequence>
              <s:element minOccurs="1" maxOccurs="1" name="StatusExecucao" type="s:int" />
            </s:sequence>
          </s:extension>
        </s:complexContent>
      </s:complexType>
      <s:element name="RemoverIdentificador">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="request" type="tns:FinanceiroRequest" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="RemoverIdentificadorResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="RemoverIdentificadorResult" type="tns:FinanceiroResponse" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="CriarIdentificadores">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="1" maxOccurs="1" name="quantidade" type="s:int" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:complexType name="ArrayOfString">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="unbounded" name="string" nillable="true" type="s:string" />
        </s:sequence>
      </s:complexType>
      <s:element name="CriarIdentificadoresResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="CriarIdentificadoresResult" type="tns:IdentificadoresResponse" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:complexType name="IdentificadoresResponse">
        <s:complexContent mixed="false">
          <s:extension base="tns:Response">
            <s:sequence>
              <s:element minOccurs="0" maxOccurs="1" name="Identificadores" type="tns:ArrayOfString" />
            </s:sequence>
          </s:extension>
        </s:complexContent>
      </s:complexType>
      <s:element name="Login">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="userName" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="password" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="LoginResponse">
        <s:complexType />
      </s:element>
    </s:schema>
  </wsdl:types>
  <wsdl:message name="IntegrarSoapIn">
    <wsdl:part name="parameters" element="tns:Integrar" />
  </wsdl:message>
  <wsdl:message name="IntegrarSoapOut">
    <wsdl:part name="parameters" element="tns:IntegrarResponse" />
  </wsdl:message>
  <wsdl:message name="IntegrarAgendadoSoapIn">
    <wsdl:part name="parameters" element="tns:IntegrarAgendado" />
  </wsdl:message>
  <wsdl:message name="IntegrarAgendadoSoapOut">
    <wsdl:part name="parameters" element="tns:IntegrarAgendadoResponse" />
  </wsdl:message>
  <wsdl:message name="ExcluirSoapIn">
    <wsdl:part name="parameters" element="tns:Excluir" />
  </wsdl:message>
  <wsdl:message name="ExcluirSoapOut">
    <wsdl:part name="parameters" element="tns:ExcluirResponse" />
  </wsdl:message>
  <wsdl:message name="ExcluirAgendadoSoapIn">
    <wsdl:part name="parameters" element="tns:ExcluirAgendado" />
  </wsdl:message>
  <wsdl:message name="ExcluirAgendadoSoapOut">
    <wsdl:part name="parameters" element="tns:ExcluirAgendadoResponse" />
  </wsdl:message>
  <wsdl:message name="BloquearSoapIn">
    <wsdl:part name="parameters" element="tns:Bloquear" />
  </wsdl:message>
  <wsdl:message name="BloquearSoapOut">
    <wsdl:part name="parameters" element="tns:BloquearResponse" />
  </wsdl:message>
  <wsdl:message name="BloquearAgendadoSoapIn">
    <wsdl:part name="parameters" element="tns:BloquearAgendado" />
  </wsdl:message>
  <wsdl:message name="BloquearAgendadoSoapOut">
    <wsdl:part name="parameters" element="tns:BloquearAgendadoResponse" />
  </wsdl:message>
  <wsdl:message name="DesbloquearSoapIn">
    <wsdl:part name="parameters" element="tns:Desbloquear" />
  </wsdl:message>
  <wsdl:message name="DesbloquearSoapOut">
    <wsdl:part name="parameters" element="tns:DesbloquearResponse" />
  </wsdl:message>
  <wsdl:message name="DesbloquearAgendadoSoapIn">
    <wsdl:part name="parameters" element="tns:DesbloquearAgendado" />
  </wsdl:message>
  <wsdl:message name="DesbloquearAgendadoSoapOut">
    <wsdl:part name="parameters" element="tns:DesbloquearAgendadoResponse" />
  </wsdl:message>
  <wsdl:message name="CancelarSoapIn">
    <wsdl:part name="parameters" element="tns:Cancelar" />
  </wsdl:message>
  <wsdl:message name="CancelarSoapOut">
    <wsdl:part name="parameters" element="tns:CancelarResponse" />
  </wsdl:message>
  <wsdl:message name="CancelarAgendadoSoapIn">
    <wsdl:part name="parameters" element="tns:CancelarAgendado" />
  </wsdl:message>
  <wsdl:message name="CancelarAgendadoSoapOut">
    <wsdl:part name="parameters" element="tns:CancelarAgendadoResponse" />
  </wsdl:message>
  <wsdl:message name="ConsultarIntegracaoSoapIn">
    <wsdl:part name="parameters" element="tns:ConsultarIntegracao" />
  </wsdl:message>
  <wsdl:message name="ConsultarIntegracaoSoapOut">
    <wsdl:part name="parameters" element="tns:ConsultarIntegracaoResponse" />
  </wsdl:message>
  <wsdl:message name="ConsultarFuncaoSoapIn">
    <wsdl:part name="parameters" element="tns:ConsultarFuncao" />
  </wsdl:message>
  <wsdl:message name="ConsultarFuncaoSoapOut">
    <wsdl:part name="parameters" element="tns:ConsultarFuncaoResponse" />
  </wsdl:message>
  <wsdl:message name="RemoverIdentificadorSoapIn">
    <wsdl:part name="parameters" element="tns:RemoverIdentificador" />
  </wsdl:message>
  <wsdl:message name="RemoverIdentificadorSoapOut">
    <wsdl:part name="parameters" element="tns:RemoverIdentificadorResponse" />
  </wsdl:message>
  <wsdl:message name="CriarIdentificadoresSoapIn">
    <wsdl:part name="parameters" element="tns:CriarIdentificadores" />
  </wsdl:message>
  <wsdl:message name="CriarIdentificadoresSoapOut">
    <wsdl:part name="parameters" element="tns:CriarIdentificadoresResponse" />
  </wsdl:message>
  <wsdl:message name="LoginSoapIn">
    <wsdl:part name="parameters" element="tns:Login" />
  </wsdl:message>
  <wsdl:message name="LoginSoapOut">
    <wsdl:part name="parameters" element="tns:LoginResponse" />
  </wsdl:message>
  <wsdl:portType name="FinanceiroServiceSoap">
    <wsdl:operation name="Integrar">
      <wsdl:documentation xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">Integra uma lista de documentos</wsdl:documentation>
      <wsdl:input message="tns:IntegrarSoapIn" />
      <wsdl:output message="tns:IntegrarSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="IntegrarAgendado">
      <wsdl:documentation xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">Integra uma lista de documentos de forma assincrona</wsdl:documentation>
      <wsdl:input message="tns:IntegrarAgendadoSoapIn" />
      <wsdl:output message="tns:IntegrarAgendadoSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="Excluir">
      <wsdl:documentation xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">Exclui uma lista de documentos</wsdl:documentation>
      <wsdl:input message="tns:ExcluirSoapIn" />
      <wsdl:output message="tns:ExcluirSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="ExcluirAgendado">
      <wsdl:documentation xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">Exclui uma lista de documentos de forma assincrona</wsdl:documentation>
      <wsdl:input message="tns:ExcluirAgendadoSoapIn" />
      <wsdl:output message="tns:ExcluirAgendadoSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="Bloquear">
      <wsdl:documentation xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">Bloqueia uma lista de documentos</wsdl:documentation>
      <wsdl:input message="tns:BloquearSoapIn" />
      <wsdl:output message="tns:BloquearSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="BloquearAgendado">
      <wsdl:documentation xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">Bloqueia uma lista de documentos de forma assincrona</wsdl:documentation>
      <wsdl:input message="tns:BloquearAgendadoSoapIn" />
      <wsdl:output message="tns:BloquearAgendadoSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="Desbloquear">
      <wsdl:documentation xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">Desbloqueia uma lista de documentos</wsdl:documentation>
      <wsdl:input message="tns:DesbloquearSoapIn" />
      <wsdl:output message="tns:DesbloquearSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="DesbloquearAgendado">
      <wsdl:documentation xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">Desbloquear uma lista de documentos de forma assincrona</wsdl:documentation>
      <wsdl:input message="tns:DesbloquearAgendadoSoapIn" />
      <wsdl:output message="tns:DesbloquearAgendadoSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="Cancelar">
      <wsdl:documentation xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">Cancela uma lista de documentos</wsdl:documentation>
      <wsdl:input message="tns:CancelarSoapIn" />
      <wsdl:output message="tns:CancelarSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="CancelarAgendado">
      <wsdl:documentation xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">Cancela uma lista de documentos de forma assincrona</wsdl:documentation>
      <wsdl:input message="tns:CancelarAgendadoSoapIn" />
      <wsdl:output message="tns:CancelarAgendadoSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="ConsultarIntegracao">
      <wsdl:documentation xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">Consulta o status e os documentos integrados anteriormente</wsdl:documentation>
      <wsdl:input message="tns:ConsultarIntegracaoSoapIn" />
      <wsdl:output message="tns:ConsultarIntegracaoSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="ConsultarFuncao">
      <wsdl:documentation xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">Consulta o resultado de exclusão/confirmação/bloqueio executado anteriormente</wsdl:documentation>
      <wsdl:input message="tns:ConsultarFuncaoSoapIn" />
      <wsdl:output message="tns:ConsultarFuncaoSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="RemoverIdentificador">
      <wsdl:documentation xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">Remove o identificador de processamento. Não desfaz as alterações feitas pelo processamento.</wsdl:documentation>
      <wsdl:input message="tns:RemoverIdentificadorSoapIn" />
      <wsdl:output message="tns:RemoverIdentificadorSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="CriarIdentificadores">
      <wsdl:documentation xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">Cria identificadores únicos baseados em Guid</wsdl:documentation>
      <wsdl:input message="tns:CriarIdentificadoresSoapIn" />
      <wsdl:output message="tns:CriarIdentificadoresSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="Login">
      <wsdl:documentation xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">Faz a autenticação de usuário necessária para execução de todos métodos.</wsdl:documentation>
      <wsdl:input message="tns:LoginSoapIn" />
      <wsdl:output message="tns:LoginSoapOut" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="FinanceiroServiceSoap" type="tns:FinanceiroServiceSoap">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="Integrar">
      <soap:operation soapAction="http://Benner.Corporativo.WebServices.DataContracts/2010/10/Integrar" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="IntegrarAgendado">
      <soap:operation soapAction="http://Benner.Corporativo.WebServices.DataContracts/2010/10/IntegrarAgendado" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Excluir">
      <soap:operation soapAction="http://Benner.Corporativo.WebServices.DataContracts/2010/10/Excluir" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ExcluirAgendado">
      <soap:operation soapAction="http://Benner.Corporativo.WebServices.DataContracts/2010/10/ExcluirAgendado" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Bloquear">
      <soap:operation soapAction="http://Benner.Corporativo.WebServices.DataContracts/2010/10/Bloquear" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="BloquearAgendado">
      <soap:operation soapAction="http://Benner.Corporativo.WebServices.DataContracts/2010/10/BloquearAgendado" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Desbloquear">
      <soap:operation soapAction="http://Benner.Corporativo.WebServices.DataContracts/2010/10/Desbloquear" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="DesbloquearAgendado">
      <soap:operation soapAction="http://Benner.Corporativo.WebServices.DataContracts/2010/10/DesbloquearAgendado" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Cancelar">
      <soap:operation soapAction="http://Benner.Corporativo.WebServices.DataContracts/2010/10/Cancelar" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="CancelarAgendado">
      <soap:operation soapAction="http://Benner.Corporativo.WebServices.DataContracts/2010/10/CancelarAgendado" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ConsultarIntegracao">
      <soap:operation soapAction="http://Benner.Corporativo.WebServices.DataContracts/2010/10/ConsultarIntegracao" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ConsultarFuncao">
      <soap:operation soapAction="http://Benner.Corporativo.WebServices.DataContracts/2010/10/ConsultarFuncao" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="RemoverIdentificador">
      <soap:operation soapAction="http://Benner.Corporativo.WebServices.DataContracts/2010/10/RemoverIdentificador" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="CriarIdentificadores">
      <soap:operation soapAction="http://Benner.Corporativo.WebServices.DataContracts/2010/10/CriarIdentificadores" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Login">
      <soap:operation soapAction="http://Benner.Corporativo.WebServices.DataContracts/2010/10/Login" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:binding name="FinanceiroServiceSoap12" type="tns:FinanceiroServiceSoap">
    <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="Integrar">
      <soap12:operation soapAction="http://Benner.Corporativo.WebServices.DataContracts/2010/10/Integrar" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="IntegrarAgendado">
      <soap12:operation soapAction="http://Benner.Corporativo.WebServices.DataContracts/2010/10/IntegrarAgendado" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Excluir">
      <soap12:operation soapAction="http://Benner.Corporativo.WebServices.DataContracts/2010/10/Excluir" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ExcluirAgendado">
      <soap12:operation soapAction="http://Benner.Corporativo.WebServices.DataContracts/2010/10/ExcluirAgendado" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Bloquear">
      <soap12:operation soapAction="http://Benner.Corporativo.WebServices.DataContracts/2010/10/Bloquear" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="BloquearAgendado">
      <soap12:operation soapAction="http://Benner.Corporativo.WebServices.DataContracts/2010/10/BloquearAgendado" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Desbloquear">
      <soap12:operation soapAction="http://Benner.Corporativo.WebServices.DataContracts/2010/10/Desbloquear" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="DesbloquearAgendado">
      <soap12:operation soapAction="http://Benner.Corporativo.WebServices.DataContracts/2010/10/DesbloquearAgendado" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Cancelar">
      <soap12:operation soapAction="http://Benner.Corporativo.WebServices.DataContracts/2010/10/Cancelar" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="CancelarAgendado">
      <soap12:operation soapAction="http://Benner.Corporativo.WebServices.DataContracts/2010/10/CancelarAgendado" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ConsultarIntegracao">
      <soap12:operation soapAction="http://Benner.Corporativo.WebServices.DataContracts/2010/10/ConsultarIntegracao" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ConsultarFuncao">
      <soap12:operation soapAction="http://Benner.Corporativo.WebServices.DataContracts/2010/10/ConsultarFuncao" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="RemoverIdentificador">
      <soap12:operation soapAction="http://Benner.Corporativo.WebServices.DataContracts/2010/10/RemoverIdentificador" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="CriarIdentificadores">
      <soap12:operation soapAction="http://Benner.Corporativo.WebServices.DataContracts/2010/10/CriarIdentificadores" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Login">
      <soap12:operation soapAction="http://Benner.Corporativo.WebServices.DataContracts/2010/10/Login" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="FinanceiroService">
    <wsdl:documentation xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">Integração do módulo financeiro do sistema Corporativo</wsdl:documentation>
    <wsdl:port name="FinanceiroServiceSoap" binding="tns:FinanceiroServiceSoap">
      <soap:address location="http://localhost/WebApp/NonAuthenticatedServiceHost/FinanceiroService.asmx" />
    </wsdl:port>
    <wsdl:port name="FinanceiroServiceSoap12" binding="tns:FinanceiroServiceSoap12">
      <soap12:address location="http://localhost/WebApp/NonAuthenticatedServiceHost/FinanceiroService.asmx" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>